export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const ADS_LOAD_REQUEST = 'ADS_LOAD_REQUEST'
export const ADS_LOAD_SUCCESS = 'ADS_LOAD_SUCCESS'
export const ADS_LOAD_FAIL = 'ADS_LOAD_FAIL'
export const ADS_GET_TAGS = 'ADS_GET_TAGS'

export const AD_CREATE_SUCCESS = 'AD_CREATE_SUCCESS'
export const AD_DELETE_SUCCESS = 'AD_DELETE_SUCCESS'
export const AD_GET_BY_ID = 'AD_GET_BY_ID'

export const UI_RESET_ERROR = 'UI_RESET_ERROR'
