export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const ADS_LOAD_REQUEST = 'ADS_LOAD_REQUEST'
export const ADS_LOAD_SUCCESS = 'ADS_LOAD_SUCCESS'
export const ADS_LOAD_FAIL = 'ADS_LOAD_FAIL'

export const UI_RESET_ERROR = 'UI_RESET_ERROR'
